name: deploy-ecomm-ml

on:
  pull_request:
    branches:
      - main
  # push:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0/6 * * *' # Execute every 6 hours
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Access the repo (Checkout)
        uses: actions/checkout@v2 # using the "checkout" action

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Trigger Google Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecomm-ml

